@startuml
'https://plantuml.com/class-diagram

title iterator pattern

class BookShelf {
- Book[] books
- int last = 0

+ Book getBookAt(int index)
+ void appendBook(Book book)
+ int getLength()
+ BookShelfIterator iterator()
}

class BookShelfIterator {
- BookShelf bookShelf
- int index

+ boolean hasNext()
+ Book next()
}

class Book {
- String name
+ String getName()
}

interface Iterator<T> {
+ boolean hasNext()
+ T next()
}

interface Iterable<T> {
+ Iterator<T> iterator()
}


Iterable - Iterator : create >
BookShelf ..|> Iterable
BookShelfIterator ..|> Iterator
BookShelf <-o BookShelfIterator
Book <--o BookShelf


@enduml